name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install Node
        run: npm install
      - run: npm run test:unit
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install Node
        run: npm install
      - run: npm ci
  DockerBuild : 
    runs-on : ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#       -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest

